FROM node:16.16.0-alpine

WORKDIR /oadp/

RUN npm install -g cspell@latest

CMD cspell "**" \
    --gitignore \
    --dot \
    --show-suggestions

# docker image build --tag cspell - < Dockerfile.cspell
# docker container run --rm -it -v "./oadp/:/oadp" cspell
