:sectlinks:
:markup-in-source: verbatim,attributes,quotes
:OCP4_PASSWORD: %ocp4_password%
:CLUSTER_ADMIN_USER: %cluster_admin_user%
:CLUSTER_ADMIN_PASSWORD: %cluster_admin_password%
:APPS_URL: %apps_url%
:API_URL: %api_url%

== Backing up a stateful Application using VolumeSnapshotMover

We are going to protecting a simple Todo web-based application front-end, backed by MariaDB . This application has been pre-deployed on your OCP 4 cluster in the `mysql-persistent` namespace.

OADP Data Mover enables customers to back up container storage interface (CSI) volume snapshots to a remote object store. When Data Mover is enabled, you can restore stateful applications from the store if a failure, accidental deletion, or corruption of the cluster occurs. OADP Data Mover solution uses the Restic option of VolSync.

=== Prerequisites: 


Create appropriate `volumeSnapshotClass` and `storageClass`
`gp2-csi` comes as a defualt `StorageClass` with Openshift Cluster. 

[source,bash,role=execute]
----
oc get storageclass gp2-csi
----

Include a label in `VolumeSnapshotClass` to let Velero know which to use, and set `deletionPolicy` to `Retain` in order for VolumeSnapshotContent to remain after the application namespace is deleted.
As a part of the deployment, oadp-example-snapclass `VolumentSnapshotClass` is created. To varify label

[source,bash,role=execute]
----
oc get volumesnapshotclass oadp-snapclass -o yaml
----


Verify pre-deployed Volsync resources

[source,bash,role=execute]
----
oc get deployments -n openshift-operators
----

We will be using VolSync's Restic option, hence we configured a restic secret `dm-credentials`
Verify `dm-credentials`

[source,bash,role=execute]
----
oc get secrets dm-credentials -n openshift-adp
----

Verify DPA 

[source,bash,role=execute]
----
oc get dpa -n openshift-adp -o yaml 
----

Note dm-credentials is set in DPA CR at `spec.features.dataMover.credentialName`. If this step is not completed then it will default to the secret name `dm-credential`. And, the CSI and VSM as `defaultPlugins` and `dataMover.enable` flag.

=== Backup create 