:sectlinks:
:markup-in-source: verbatim,attributes,quotes
:OCP4_GUID: %ocp4_guid%
:OCP4_DOMAIN: %ocp4_domain%
:OCP4_SSH_USER: %ocp4_ssh_user%
:OCP4_PASSWORD: %ocp4_password%

== Backing up multiple namespaces

In previous exercise, we backed up a single namespace using `--include-namespaces` flag from Velero CLI. This flag actually accepts a `stringArray`. We can backup multiple namespaces using the flag separating them by `,`.

In addition to the Microsoft SQL Server application, we have pre-deployed for you a second application called `parks-app`. This application has been pre-deployed on your OCP 4 cluster in the `parks-app` namespace, using a single PV backed by NFS for persistent storage.

In our source OCP 4 cluster terminal, we can see the app running:

[source,bash,role=execute]
----
oc get pods -n parks-app
----

[source,subs="{markup-in-source}"]
--------------------------------------------------------------------------------
NAME               READY   STATUS      RESTARTS   AGE
mongodb-1-qb6xw    1/1     Running     0          22h
restify-1-fc59d    1/1     Running     0          22h
--------------------------------------------------------------------------------

Check that Microsoft SQL Server Application is still running.
[source,bash,role=execute]
----
oc get pods -n mssql-persistent
----
[source,subs="{markup-in-source}"]
--------------------------------------------------------------------------------
NAME                                    READY   STATUS    RESTARTS   AGE
mssql-app-deployment-6ffb46c5d6-n5fvv   1/1     Running   0          41m
mssql-deployment-1-xq4p4                1/1     Running   0          41m
--------------------------------------------------------------------------------

Let’s checkout the route to the applications user interfaces.

[source,bash,role=execute]
----
oc get route -n parks-app
----
[source,bash,role=execute]
----
oc get route -n mssql-persistent
----
NOTE: You can also use links here to open application routes http://mssql-app-route-mssql-persistent.apps.cluster-{OCP4_GUID}.{OCP4_GUID}.{OCP4_DOMAIN}[mssql-app] and http://restify-parks-app.apps.cluster-{OCP4_GUID}.{OCP4_GUID}.{OCP4_DOMAIN}[parks-app].

Check that the routes are working correctly then proceed to the next section.

=== Using Velero to backup application namespaces

Let’s go ahead and create a backup of `mssql-persistent` and `parks-app` namespace.
[source,bash,role=execute-2]
----
velero backup create two-ns-backup --include-namespaces mssql-persistent,parks-app -n openshift-adp
----

You can check on the backup progress by running the following
[source,bash,role=execute]
----
velero backup describe two-ns-backup -n openshift-adp
----
When the backup is finished, proceed to next section.

=== Simulate a disaster
When the backup is finished, we'll proceed to simulate a disaster by deleting the two namespaces.
[source,bash,role=execute]
----
oc delete ns mssql-persistent parks-app
----

Check that the applications are no longer available.

NOTE: You can also use links here to open application routes http://mssql-app-route-mssql-persistent.apps.cluster-{OCP4_GUID}.{OCP4_GUID}.{OCP4_DOMAIN}[mssql-app] and http://restify-parks-app.apps.cluster-{OCP4_GUID}.{OCP4_GUID}.{OCP4_DOMAIN}[parks-app].

When application is no longer available, proceed to next section.

=== Restoring deleted application
We can restore applications deleted earlier by restoring from the backup we created.
[source,bash,role=execute]
----
velero restore create two-ns-restore --from-backup two-ns-backup -n openshift-adp
----

[source,bash,role=execute]
----
velero restore describe two-ns-restore -n openshift-adp
----

Wait until pods become available.
[source,bash,role=execute]
----
oc get pods -n mssql-persistent
----
[source,bash,role=execute]
----
oc get pods -n parks-app
----

Verify that the data you added earlier persisted in the restored application.

NOTE: You can also use links here to open application routes http://mssql-app-route-mssql-persistent.apps.cluster-{OCP4_GUID}.{OCP4_GUID}.{OCP4_DOMAIN}[mssql-app] and http://restify-parks-app.apps.cluster-{OCP4_GUID}.{OCP4_GUID}.{OCP4_DOMAIN}[parks-app].