:sectlinks:
:markup-in-source: verbatim,attributes,quotes
:OCP4_PASSWORD: %ocp4_password%
:CLUSTER_ADMIN_USER: %cluster_admin_user%
:APPS_URL: %apps_url%
:API_URL: %api_url%

== Backing up multiple namespaces

In previous exercise, we backed up a single namespace using `--include-namespaces` flag from Velero CLI. This flag actually accepts a `stringArray`. We can backup multiple namespaces using the flag separating them by `,`.

In addition to the Microsoft SQL Server application, we have pre-deployed for you a second application called `parks-app`. This application has been pre-deployed on your OCP 4 cluster in the `parks-app` namespace, using a single PV backed by NFS for persistent storage.

In our source OCP 4 cluster terminal, we can see the app running:

[source,bash,role=execute]
----
oc get pods -n parks-app
----

[source,subs="{markup-in-source}"]
--------------------------------------------------------------------------------
NAME               READY   STATUS      RESTARTS   AGE
mongodb-1-qb6xw    1/1     Running     0          22h
restify-1-fc59d    1/1     Running     0          22h
--------------------------------------------------------------------------------

Check that Microsoft SQL Server Application is still running.
[source,bash,role=execute]
----
oc get pods -n mssql-persistent
----
[source,subs="{markup-in-source}"]
--------------------------------------------------------------------------------
NAME                                    READY   STATUS    RESTARTS   AGE
mssql-app-deployment-6ffb46c5d6-n5fvv   1/1     Running   0          41m
mssql-deployment-1-xq4p4                1/1     Running   0          41m
--------------------------------------------------------------------------------

Let’s checkout the route to the applications user interfaces.

[source,bash,role=execute]
----
oc get route -n parks-app
----
[source,bash,role=execute]
----
oc get route -n mssql-persistent
----
NOTE: You can also use links here to open application routes http://mssql-app-route-mssql-persistent.{APPS_URL}[mssql-app] and http://restify-parks-app.{APPS_URL}[parks-app].

Check that the routes are working correctly then proceed to the next section.

=== Using Velero to backup application namespaces

Let’s go ahead and create a backup of `mssql-persistent` and `parks-app` namespace.
[source,bash,role=execute-2]
----
velero backup create two-ns-backup --include-namespaces mssql-persistent,parks-app -n openshift-adp
----

You can check on the backup progress by running the following
[source,bash,role=execute]
----
velero backup describe two-ns-backup -n openshift-adp
----
When the backup is finished, proceed to next section.

=== Viewing backup content in S3 storage
Backup content is stored in S3 storage in the specified content in the prefix location under folder backup inside the backup name's folder.

`<bucket>/<velero-prefix>/backups/<backup-name>/<backup-content>`

[source,bash,role=execute]
----
awsocs s3 ls migstorage/velero/backups/two-ns-backup/
----
=== A snapshot was taken
When a backup includes a persistent volume claim, a snapshot is created provided you have configured Velero to take snapshots.


=== About Velero CSI Snapshots
The backup we did just now of the parks-app and mssql namespace used CSI snapshot capability of Velero to create snapshot on AWS EBS and OpenShift Storage Ceph Rados Block Device (RBD) using their respective CSI Drivers

The details were explained in the first exercise.

The namespace parks-app we backup earlier contained a persistent volume claim that has storage class `gp2-csi` so that the snapshot was created using the AWS EBS CSI Driver.

View persistent volume claim in the namespace `mssql-persistent` and `parks-app`.
[source,bash,role=execute]
----
oc get pvc -n mssql-persistent
oc get pvc -n parks-app
----
View VolumeSnapshot taken.
[source,bash,role=execute]
----
NEWEST_VS_MSSQL=$(oc get volumesnapshot -n mssql-persistent --sort-by=.metadata.creationTimestamp -o name | tail -n 1)
NEWEST_VS_PARKS=$(oc get volumesnapshot -n parks-app --sort-by=.metadata.creationTimestamp -o name | tail -n 1)
oc get $NEWEST_VS_MSSQL -n mssql-persistent 
oc get $NEWEST_VS_PARKS -n parks-app
----
View VolumeSnapshotContent created.
[source,bash,role=execute]
----
MSSQL_VS_CONTENT_NAME=$(oc get $NEWEST_VS_MSSQL -n mssql-persistent -o go-template='{{.status.boundVolumeSnapshotContentName}}')
PARKS_VS_CONTENT_NAME=$(oc get $NEWEST_VS_PARKS -n parks-app -o go-template='{{.status.boundVolumeSnapshotContentName}}')
oc get volumesnapshotcontent $MSSQL_VS_CONTENT_NAME
oc get volumesnapshotcontent $PARKS_VS_CONTENT_NAME
----

This storage class has provisioner `ebs.csi.aws.com`
[source,bash,role=execute]
----
oc get storageclass gp2-csi
----

which is one of the CSI driver installed on the system
[source,bash,role=execute]
----
oc get csidrivers
----

CSI Snapshot is local to the cluster. In the future, a DataMover capability will be added to allow for moving snapshots to an external location.

=== Simulate a disaster
When the backup is finished, we'll proceed to simulate a disaster by deleting the two namespaces.
[source,bash,role=execute]
----
oc delete ns mssql-persistent parks-app
----

Check that the applications are no longer available.

NOTE: You can also use links here to open application routes http://mssql-app-route-mssql-persistent.{APPS_URL}[mssql-app] and http://restify-parks-app.{APPS_URL}[parks-app].

When application is no longer available, proceed to next section.

=== Restoring deleted application
We can restore applications deleted earlier by restoring from the backup we created.
[source,bash,role=execute]
----
velero restore create two-ns-restore --from-backup two-ns-backup -n openshift-adp
----

[source,bash,role=execute]
----
velero restore describe two-ns-restore -n openshift-adp
----

Wait until pods become available.
[source,bash,role=execute]
----
oc get pods -n mssql-persistent
----
[source,bash,role=execute]
----
oc get pods -n parks-app
----

Verify that the data you added earlier persisted in the restored application.

NOTE: You can also use links here to open application routes http://mssql-app-route-mssql-persistent.{APPS_URL}[mssql-app] and http://restify-parks-app.{APPS_URL}[parks-app].
